# Docker compose up reads this override automatically. This file is used for local development

services:
  django-web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
    command: python manage.py runserver 0.0.0.0:8000

  ml-service:
    build:
      context: ./ml_project
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      DEBUG: 1
    command: python manage.py runserver 0.0.0.0:8001
