# Generated by Django 5.1.7 on 2025-03-19 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactinfo_model_price_per_prediction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('model_id', models.AutoField(db_column='ModelID', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, db_column='ModelName', max_length=255, null=True)),
                ('model_type', models.CharField(blank=True, db_column='ModelType', max_length=255, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=255, null=True)),
                ('filepath', models.CharField(blank=True, db_column='FilePath', max_length=255, null=True)),
                ('price_per_prediction', models.FloatField(blank=True, db_column='PricePerPrediction', null=True)),
            ],
            options={
                'db_table': 'PredictionModel',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='uploadedrecord',
            name='model_id',
            field=models.ForeignKey(blank=True, db_column='ModelID', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.predictionmodel'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
