# Generated by Django 5.1.7 on 2025-03-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_predictionmodel_alter_uploadedrecord_model_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingStep',
            fields=[
                ('preprocessing_step_id', models.AutoField(db_column='PreprocessingStepID', primary_key=True, serialize=False)),
                ('preprocess_name', models.CharField(blank=True, db_column='PreprocessName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PreprocessingStep',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PreprocessingModelMap',
            fields=[
                ('preprocessing_model_map_id', models.AutoField(db_column='PreprocessingModelMapID', primary_key=True, serialize=False)),
                ('model_id', models.ForeignKey(blank=True, db_column='ModelID', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.predictionmodel')),
                ('preprocessing_step_id', models.ForeignKey(blank=True, db_column='PreprocessingStepID', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.preprocessingstep')),
            ],
            options={
                'db_table': 'PreprocessingModelMap',
                'managed': True,
            },
        ),
    ]
