# Generated by Django 5.1.7 on 2025-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_preprocessingstep_preprocessingmodelmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_company_owner',
            field=models.BooleanField(blank=True, db_column='IsCompanyOwner', null=True),
        ),
    ]
