# Generated by Django 5.1.7 on 2025-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_accidentdate_claim_accident_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedrecord',
            name='user_settlement',
            field=models.FloatField(blank=True, db_column='UserSettlement', null=True),
        ),
    ]
