# Generated by Django 5.1.7 on 2025-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_financereport_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='created_at',
            field=models.DateField(db_column='CreatedAt', default='2025-04-18'),
            preserve_default=False,
        ),
    ]
