# Generated by Django 5.1.7 on 2025-04-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_financereport_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financereport',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt'),
        ),
    ]
