# Generated by Django 5.1.7 on 2025-04-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_financereport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='user_profile_id',
            field=models.ForeignKey(blank=True, db_column='UserProfileID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_as_subject', to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='financereport',
            name='company_id',
            field=models.ForeignKey(blank=True, db_column='CompanyID', null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='financereport',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_created', to='myapp.userprofile'),
        ),
    ]
