# Generated by Django 5.1.7 on 2025-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_financereport_user_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financereport',
            name='paid',
            field=models.BooleanField(db_column='Paid', default=False),
        ),
    ]
